# Generated by Django 3.2.9 on 2021-11-29 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currsos.alumnos')),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('alumnos', models.ManyToManyField(through='currsos.Asignacion', to='currsos.Alumnos')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion',
            name='cursos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currsos.cursos'),
        ),
    ]
